/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val name = "Alfian"

    print("Hello my name is ")
    println(name)
    print(if (true) "Always true" else "Always false")
}
